[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
solc_version = '0.8.20'

# Testing
block_number = 19537700 # Mar-29-2024 05:52:47 AM +UTC

# Define RPC urls as RPC_{ChainID}
[rpc_endpoints]
mainnet = "${RPC_1}" 
